
DROP DATABASE IF EXISTS speakit_db;
CREATE DATABASE speakit_db;
USE speakit_db;

CREATE TABLE user (
  id INTEGER AUTO_INCREMENT NOT NULL,
  burger_name VARCHAR(300),
  devoured BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (id)
)

